version: '2'

services:
  market_service:
    ports:
      - "7732:7732"
    build:
      context: .
      dockerfile: core/Dockerfile
    restart: unless-stopped
    container_name: market_service
  market_postgres:
    image: postgres:latest
    container_name: market_postgres
    ports:
      - "5876:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=market
      - POSTGRES_PASSWORD=TestPwd
    restart: unless-stopped
  market_redis:
    image: redis:6.2-alpine
    container_name: market_redis
    restart: always
    ports:
      - '6387:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass TestPwd