apiVersion: v1
kind: PersistentVolume
metadata:
  name: core-postgres-volume
  labels:
    type: local
    app: core-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql