apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: default
spec:
  ports:
    - port: 7733
      protocol: TCP
      targetPort: 7733
  selector:
    name: auth
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: default
spec:
  ports:
    - port: 7732
      protocol: TCP
      targetPort: 7732
  selector:
    name: core
  sessionAffinity: None
  type: LoadBalancer