apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-redis-volume-claim
  labels:
    app: auth-redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi